# ARTIE-I manager parameters
manager:
    number_of_threads:  8
    number_of_runs:     1
    number_of_events:   1000000
    mode:               "run"   # interactive/run
    detector:           "artieI"
    output_filename:    "artieI_argon"
    save_particle_maps: true
    save_primary_info:  true
    save_hits:          true
    save_neutron_data:  true

# ARTIE-I detector parameters
detector:
    active_volume_material:         "liquid_argon"
    target_radius: 1.25             # cm
    target_length: 168              # cm
    construct_container: true       # bool
    container_radius: 1.745         # cm
    insulation_thickness: 10        # cm
    window_thickness: 0.00762       # cm
    buffer_length: 5.0              # cm
    beam_pipe_inner_radius: 18.0    # cm
    beam_pipe_outer_radius: 20.0    # cm
    gap: 2.5        # m
    world_x: 4      # m                 
    world_y: 4      # m
    world_z: 200    # m
    wall_thickness: 1.0     # m
    detector_radius: 2.0    # cm
    detector_length: 20.0   # cm
    detector_entrance: 69.0 # m
    
# ARTIE-I generator parameters
generator:
    use_lanl_distribution: true
    lanl_distribution_filename: "resolution13a.root"
    lanl_distribution_name: "tally5"
    t_zero_location: -1.0   # m
    energy_cut_low: 40      # keV
    energy_cut_high: 70     # keV