# ARTIE-I manager parameters
manager:
    number_of_threads:  8
    number_of_runs:     1
    number_of_events:   1000000
    mode:               "run"   # interactive/run
    detector:           "artieI"
    output_filename:    "artieI_ideal"
    save_particle_maps: true
    save_primary_info:  true
    save_hits:          true
    save_neutron_data:  true

# ARTIE-I detector parameters
detector:
    active_volume_material:         "liquid_argon"
    target_radius: 1.25             # cm
    target_length: 168              # cm
    construct_container: false       # bool
    construct_beam_pipe: false       # bool
    construct_hall: false # bool
    construct_detector: true # bool
    detector_radius: 2.0    # cm
    detector_length: 20.0   # cm
    detector_entrance: 69.0 # m
    world_material: "high_vacuum"
    
# ARTIE-I generator parameters
generator:
    use_lanl_distribution: true
    lanl_distribution_filename: "resolution13a.root"
    lanl_distribution_name: "tally5"
    t_zero_location: -1.0   # m
    energy_cut_low: 50      # keV
    energy_cut_high: 60     # keV