# ARTIE manager parameters
manager:
    number_of_threads:  8
    number_of_runs:     1
    number_of_events:   5000000
    seed:               10942
    mode:               "run"   # interactive/run
    detector:           "artieII"
    output_filename:    "artieII_ntof_vacuum_scuba_high"
    save_particle_maps: true
    save_primary_info:  true
    save_hits:          true
    save_neutron_data:   true

# ARTIE argon parameters 
argon:
    use_g4_definition:  false
    argon_36_ratio:     0.334   # %
    argon_38_ratio:     0.063   # %
    argon_40_ratio:     99.603  # %
    # density for 224 atmospheres of gaseous argon at 300K.
    lar_density:        0.182  # g/cm^3
    lar_temperature:    85.0    # K
    lar_pressure:       0.952   # atm

# ARTIE-II target parameters
# all entrances are with respect to the 
# t-zero location.  
target:
    active_volume_material: "high_vacuum"
    target_radius:          10.00    # cm
    target_length:          66.675      # cm

    target_entrance:	188 # cm
    target_x:	        0.0 # cm
    target_y:	        0.0 # cm

    construct_scuba_tank:    true
    scuba_tank_radius:       10.16
    scuba_tank_length:       66.675

hall:
    # construct_beam_pipe:    true    # bool
    # beam_pipe_material:     "rough_vacuum"
    # beam_material:          "high_vacuum"
    # beam_pipe_inner_radius: 18.0    # cm
    # beam_pipe_outer_radius: 20.0    # cm
    # gap:                    2.5     # m
    # construct_hall:         true    # bool
    # hall_material:          "concrete"
    world_x:                4       # m                 
    world_y:                4       # m
    world_z:                300     # m
    world_material:         "high_vacuum"
    # wall_thickness:         1.0     # m

# ARTIE-II detector
detector:
    construct_detector:     true    # bool
    detector_material:      "water"
    detector_radius:        2.0 # cm
    detector_length:        50.0 # cm
    detector_entrance:      200.0 # m

# ARTIE Filters
filters:
    construct_filters:  false                    #bool
    filter_materials:   ["aluminum", "carbon"]
    filter_z_position:  [100.0, 120.0]          # cm
    filter_thickness:   [10.0, 5.0]             # cm
    filter_radius:      [8.55218, 8.55218]      # cm

    
    
# ARTIE-I generator parameters
generator:

    # wether to use the nTOF tof for the 
    # moderator function.
    use_ntof_tof:  true
    ntof_tof_filename: "data/RF.root"
    ntof_tof_name: "histfluka"

    # wether to use the nTOF beam profile
    use_ntof_beam_profile:  true
    ntof_beam_profile_filename: "data/Profile_188m.root"
    ntof_beam_profile_name: "histfluka"
    
    t_zero_location: -188.0    # m
    energy_cut_low:  20      # keV
    energy_cut_high: 20000     # keV