# ARTIE manager parameters
manager:
    number_of_threads:  8
    number_of_runs:     1
    number_of_events:   5000000
    seed:               10942
    mode:               "run"   # interactive/run
    detector:           "artieII"
    output_filename:    "artieII_argon"
    save_particle_maps: true
    save_primary_info:  true
    save_hits:          true
    save_neutron_data:  true

# ARTIE argon parameters 
argon:
    use_g4_definition:  false
    argon_36_ratio:     0.334   # %
    argon_38_ratio:     0.063   # %
    argon_40_ratio:     99.603  # %
    lar_density:        1.3954  # g/cm^3
    lar_temperature:    85.0    # K
    lar_pressure:       0.952   # atm

# ARTIE-I detector parameters
detector:
    gdml: ARTIE_model.gdml
    active_volume: ARTIE_central tube_1.gdml
    active_volume_material: liquid_argon

    
# ARTIE-I generator parameters
generator:
    use_lanl_distribution: false
    lanl_distribution_filename: "resolution13a.root"
    lanl_distribution_name: "tally5"
    t_zero_location: -1.0   # m
    energy_cut_low:  20      # keV
    energy_cut_high: 200     # keV