# ARTIE manager parameters
manager:
    number_of_threads:  8
    number_of_runs:     1
    number_of_events:   5000000
    seed:               10942
    mode:               "run"   # interactive/run
    detector:           "artieI"
    output_filename:    "artieI_argon_long"
    save_particle_maps: true
    save_primary_info:  true
    save_hits:          true
    save_neutron_data:  true

# ARTIE argon parameters 
argon:
    use_g4_definition:  false
    argon_36_ratio:     0.334   # %
    argon_38_ratio:     0.063   # %
    argon_40_ratio:     99.603  # %
    lar_density:        1.3954  # g/cm^3
    lar_temperature:    85.0    # K
    lar_pressure:       0.952   # atm

# ARTIE-I detector parameters
detector:
    active_volume_material: "liquid_argon"
    target_radius:          1.25    # cm
    target_length:          168      # cm
    construct_container:    true    # bool
    container_material:     "stainless_steel"
    container_radius:       1.745   # cm
    insulation_material:    "polyurethane"
    insulation_thickness:   10      # cm
    window_material:        "kapton"
    window_thickness:       0.00762 # cm
    buffer_material:        "gaseous_argon"
    buffer_length:          5.0     # cm
    construct_beam_pipe:    true    # bool
    beam_pipe_material:     "rough_vacuum"
    beam_material:          "high_vacuum"
    beam_pipe_inner_radius: 18.0    # cm
    beam_pipe_outer_radius: 20.0    # cm
    gap:                    2.5     # m
    construct_hall:         true    # bool
    hall_material:          "concrete"
    world_x:                4       # m                 
    world_y:                4       # m
    world_z:                200     # m
    wall_thickness:         1.0     # m
    construct_detector:     true    # bool
    detector_material:      "water"
    detector_radius:        2.0     # cm
    detector_length:        20.0    # cm
    detector_entrance:      69.0    # m
    world_material:         "high_vacuum"
    
# ARTIE-I generator parameters
generator:
    use_lanl_distribution: false
    lanl_distribution_filename: "resolution13a.root"
    lanl_distribution_name: "tally5"
    t_zero_location: -1.0   # m
    energy_cut_low:  20      # keV
    energy_cut_high: 200     # keV